/** @type {import('tailwindcss').Config} */
// Verbatim from the user's pasted Stitch design (the inline tailwind.config).
export default {
  darkMode: "class",
  content: ["./index.html", "./src/**/*.{js,jsx}"],
  theme: {
    extend: {
      colors: {
        // ── Theme-aware tokens (light/dark via CSS vars in index.css) ──
        page: "rgb(var(--c-page) / <alpha-value>)",
        background: "rgb(var(--c-background) / <alpha-value>)",
        surface: "rgb(var(--c-surface) / <alpha-value>)",
        "surface-variant": "rgb(var(--c-surface-variant) / <alpha-value>)",
        "surface-dim": "rgb(var(--c-surface-dim) / <alpha-value>)",
        "surface-bright": "rgb(var(--c-surface-bright) / <alpha-value>)",
        "surface-container-lowest": "rgb(var(--c-surface-container-lowest) / <alpha-value>)",
        "surface-container-low": "rgb(var(--c-surface-container-low) / <alpha-value>)",
        "surface-container": "rgb(var(--c-surface-container) / <alpha-value>)",
        "surface-container-high": "rgb(var(--c-surface-container-high) / <alpha-value>)",
        "surface-container-highest": "rgb(var(--c-surface-container-highest) / <alpha-value>)",
        "on-surface": "rgb(var(--c-on-surface) / <alpha-value>)",
        "on-surface-variant": "rgb(var(--c-on-surface-variant) / <alpha-value>)",
        "on-background": "rgb(var(--c-on-background) / <alpha-value>)",
        outline: "rgb(var(--c-outline) / <alpha-value>)",
        "outline-variant": "rgb(var(--c-outline-variant) / <alpha-value>)",
        primary: "rgb(var(--c-primary) / <alpha-value>)",
        "on-primary": "rgb(var(--c-on-primary) / <alpha-value>)",
        "on-primary-container": "rgb(var(--c-on-primary-container) / <alpha-value>)",
        secondary: "rgb(var(--c-secondary) / <alpha-value>)",
        "secondary-container": "rgb(var(--c-secondary-container) / <alpha-value>)",
        "on-secondary": "rgb(var(--c-on-secondary) / <alpha-value>)",
        "on-secondary-container": "rgb(var(--c-on-secondary-container) / <alpha-value>)",
        error: "rgb(var(--c-error) / <alpha-value>)",
        "error-container": "rgb(var(--c-error-container) / <alpha-value>)",
        "on-error": "rgb(var(--c-on-error) / <alpha-value>)",
        "on-error-container": "rgb(var(--c-on-error-container) / <alpha-value>)",
        "accent-cyan": "rgb(var(--c-accent-cyan) / <alpha-value>)",

        // ── Static Material tokens not used by the UI (no theming needed) ──
        "primary-fixed": "#dfe2ee",
        "inverse-primary": "#5a5e68",
        "secondary-fixed": "#dbe1ff",
        "on-tertiary-fixed": "#261911",
        "inverse-surface": "#e5e2e2",
        "on-primary-fixed-variant": "#434750",
        "on-secondary-fixed": "#00174b",
        "primary-fixed-dim": "#c3c6d2",
        "tertiary-fixed-dim": "#dac2b6",
        "primary-container": "#080c14",
        "on-tertiary-fixed-variant": "#54433a",
        "surface-tint": "#c3c6d2",
        "inverse-on-surface": "#313031",
        "on-tertiary-container": "#8a766c",
        tertiary: "#dac2b6",
        "on-primary-fixed": "#181c24",
        "on-secondary-fixed-variant": "#003ea8",
        "tertiary-fixed": "#f7ddd1",
        "on-tertiary": "#3c2d25",
        "secondary-fixed-dim": "#b4c5ff",
        "tertiary-container": "#140904",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      spacing: {
        unit: "4px",
        "margin-desktop": "80px",
        xs: "4px",
        md: "16px",
        "3xl": "100px",
        lg: "24px",
        "2xl": "64px",
        sm: "8px",
        "margin-mobile": "20px",
        gutter: "24px",
        xl: "40px",
      },
      fontFamily: {
        "display-md": ["Plus Jakarta Sans"],
        "display-lg": ["Plus Jakarta Sans"],
        caption: ["Inter"],
        "body-md": ["Inter"],
        "body-lg": ["Inter"],
        "label-md": ["Inter"],
        "headline-lg-mobile": ["Plus Jakarta Sans"],
        "headline-lg": ["Plus Jakarta Sans"],
      },
      fontSize: {
        "display-md": ["48px", { lineHeight: "1.1", letterSpacing: "-0.03em", fontWeight: "700" }],
        "display-lg": ["64px", { lineHeight: "1.1", letterSpacing: "-0.04em", fontWeight: "700" }],
        caption: ["12px", { lineHeight: "1.4", letterSpacing: "0em", fontWeight: "400" }],
        "body-md": ["16px", { lineHeight: "1.6", letterSpacing: "0em", fontWeight: "400" }],
        "body-lg": ["18px", { lineHeight: "1.6", letterSpacing: "-0.01em", fontWeight: "400" }],
        "label-md": ["14px", { lineHeight: "1", letterSpacing: "0.05em", fontWeight: "600" }],
        "headline-lg-mobile": ["28px", { lineHeight: "1.2", letterSpacing: "-0.02em", fontWeight: "600" }],
        "headline-lg": ["32px", { lineHeight: "1.2", letterSpacing: "-0.02em", fontWeight: "600" }],
      },
    },
  },
  plugins: [],
};
