/** @type {import('tailwindcss').Config} */
// Verbatim from the user's pasted Stitch design (the inline tailwind.config).
export default {
  darkMode: "class",
  content: ["./index.html", "./src/**/*.{js,jsx}"],
  theme: {
    extend: {
      colors: {
        "on-error-container": "#ffdad6",
        "primary-fixed": "#dfe2ee",
        secondary: "#b4c5ff",
        "inverse-primary": "#5a5e68",
        error: "#ffb4ab",
        "secondary-fixed": "#dbe1ff",
        "on-primary-container": "#767a85",
        background: "#131314",
        "surface-container-lowest": "#0e0e0f",
        "on-tertiary-fixed": "#261911",
        "inverse-surface": "#e5e2e2",
        "on-primary-fixed-variant": "#434750",
        "on-surface": "#e5e2e2",
        "on-secondary-fixed": "#00174b",
        outline: "#909096",
        "surface-container-highest": "#353435",
        "primary-fixed-dim": "#c3c6d2",
        "on-secondary-container": "#cdd7ff",
        "tertiary-fixed-dim": "#dac2b6",
        "primary-container": "#080c14",
        "on-tertiary-fixed-variant": "#54433a",
        "surface-tint": "#c3c6d2",
        "inverse-on-surface": "#313031",
        "on-background": "#e5e2e2",
        "on-surface-variant": "#c6c6cc",
        "surface-bright": "#3a393a",
        "on-tertiary-container": "#8a766c",
        "on-primary": "#2c3039",
        tertiary: "#dac2b6",
        primary: "#c3c6d2",
        "surface-container-high": "#2a2a2a",
        "on-primary-fixed": "#181c24",
        "secondary-container": "#0053db",
        "surface-variant": "#353435",
        "on-secondary-fixed-variant": "#003ea8",
        "surface-dim": "#131314",
        "tertiary-fixed": "#f7ddd1",
        surface: "#131314",
        "on-tertiary": "#3c2d25",
        "error-container": "#93000a",
        "secondary-fixed-dim": "#b4c5ff",
        "on-secondary": "#002a78",
        "surface-container": "#201f20",
        "on-error": "#690005",
        "tertiary-container": "#140904",
        "surface-container-low": "#1c1b1c",
        "outline-variant": "#45474b",
        "accent-cyan": "#00f5ff",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      spacing: {
        unit: "4px",
        "margin-desktop": "80px",
        xs: "4px",
        md: "16px",
        "3xl": "100px",
        lg: "24px",
        "2xl": "64px",
        sm: "8px",
        "margin-mobile": "20px",
        gutter: "24px",
        xl: "40px",
      },
      fontFamily: {
        "display-md": ["Plus Jakarta Sans"],
        "display-lg": ["Plus Jakarta Sans"],
        caption: ["Inter"],
        "body-md": ["Inter"],
        "body-lg": ["Inter"],
        "label-md": ["Inter"],
        "headline-lg-mobile": ["Plus Jakarta Sans"],
        "headline-lg": ["Plus Jakarta Sans"],
      },
      fontSize: {
        "display-md": ["48px", { lineHeight: "1.1", letterSpacing: "-0.03em", fontWeight: "700" }],
        "display-lg": ["64px", { lineHeight: "1.1", letterSpacing: "-0.04em", fontWeight: "700" }],
        caption: ["12px", { lineHeight: "1.4", letterSpacing: "0em", fontWeight: "400" }],
        "body-md": ["16px", { lineHeight: "1.6", letterSpacing: "0em", fontWeight: "400" }],
        "body-lg": ["18px", { lineHeight: "1.6", letterSpacing: "-0.01em", fontWeight: "400" }],
        "label-md": ["14px", { lineHeight: "1", letterSpacing: "0.05em", fontWeight: "600" }],
        "headline-lg-mobile": ["28px", { lineHeight: "1.2", letterSpacing: "-0.02em", fontWeight: "600" }],
        "headline-lg": ["32px", { lineHeight: "1.2", letterSpacing: "-0.02em", fontWeight: "600" }],
      },
    },
  },
  plugins: [],
};
